### ISSUE TITLE
Boost 1.85.0

### ISSUE THREAD

**Issue by Holt59** [MarkusJx/prebuilt-boost#14]
Boost 1.85.0 is available, would be nice to be able to use it here. :)

**Comment by MarkusJx** [comment]
I've already tried building Boost 1.85.0, but the [build failed](https://github.com/MarkusJx/prebuilt-boost/actions/runs/9332524870), I'll have to investigate how to fix this.

This may take a while

**Comment by MarkusJx** [comment]
Done: https://github.com/MarkusJx/prebuilt-boost/releases/tag/1.85.0
