### ISSUE TITLE
Update Version Manifest to include 1.80 

### ISSUE THREAD

**Issue by jonassorgenfrei** [MarkusJx/prebuilt-boost#2]
Heyhey, 

i'm getting the issue: 
....
Parsing versions-manifest.json...
Error: Error: Could not find boost version 1.80.0
...

I think the versions-manifest.json needs to be updated for the new version 1.80.0 

Cheers 
Jonas

**Comment by MarkusJx** [comment]
That's actually a great point. Forgot to update the manifest, I've updated it, thanks for reporting this!
