### ISSUE TITLE
Support for macos 12?

### ISSUE THREAD

**Issue by APN-Pucky** [MarkusJx/prebuilt-boost#4]
I want to run boost with ccache from here https://github.com/cristianadam/ccache/releases, but their macos releases are only macos 12.

**Comment by MarkusJx** [comment]
I've added macos 12 to the build script and started a [test run](https://github.com/MarkusJx/prebuilt-boost/actions/runs/3639859833/jobs/6143777211) with boost 1.80.0-beta.1, let's see how this goes

**Comment by MarkusJx** [comment]
Boost version `1.80.0-beta.1` is now available built for macos 12 if you want to try it

**Comment by APN-Pucky** [comment]
hmm, I must be doing something wrong... https://github.com/APN-Pucky/tyrant_optimize/actions/runs/3641471226/jobs/6147442411
https://github.com/APN-Pucky/tyrant_optimize/blob/mac12/.github/workflows/macos.yml

Though it works with macos-11

**Comment by MarkusJx** [comment]
My bad, the correct version name is `1.80.0.beta1`. Thought it would be semver. It is not.

**Comment by APN-Pucky** [comment]
Could it be that I have to update the install-boost action version? I get missing version again.

https://github.com/APN-Pucky/tyrant_optimize/actions/runs/3641559697/jobs/6147639467

**Comment by MarkusJx** [comment]
Well that's interesting, never seen this before. No, the version is correct, you're getting a TypeError, I'll take care of this...

**Comment by APN-Pucky** [comment]
The version I ended up using before for macos-11 was 1.78.0 (soley beacuse it worked).
I think the difference between your releases is one has an arch -x86 and one does not.

**Comment by APN-Pucky** [comment]
~~If I recall correctly I also got version not found errors for 1.79 and 1.80 on ubuntu/windows, both also with the arch specified in the release archives.~~

**Comment by MarkusJx** [comment]
god dammit, I'm using semver to compare versions and since this version name is not semver compatible you get this error, wow

**Comment by MarkusJx** [comment]
`v2.4.3` should fix that issue

**Comment by APN-Pucky** [comment]
Yes, that worked. Danke. https://github.com/APN-Pucky/tyrant_optimize/actions/runs/3642296729/jobs/6149233151
