### ISSUE TITLE
1.83.0

### ISSUE THREAD

**Issue by devm18426** [MarkusJx/prebuilt-boost#6]

**Comment by MarkusJx** [comment]
Should be done in about one hour: https://github.com/MarkusJx/prebuilt-boost/actions/runs/6034969261

**Comment by MarkusJx** [comment]
Update: It was not done in about one hour, instead, it failed. And the build for version 1.82.0 didn't even start properly as GH Actions seems to be kind of down. Great.

**Comment by MarkusJx** [comment]
Done: https://github.com/MarkusJx/prebuilt-boost/releases/tag/1.83.0

**Comment by devm18426** [comment]
Amazing. Thanks
