### ISSUE TITLE
Boost 1.84.0

### ISSUE THREAD

**Issue by x-mass** [MarkusJx/prebuilt-boost#9]
Hello, @MarkusJx! Recently 1.84.0 was [released](https://github.com/boostorg/boost/releases/tag/boost-1.84.0). Could you, please, add prebuilt packages for it?
FYI, new [Cobalt](https://github.com/boostorg/cobalt/tree/master) lib requires c++20, and is being built only with `./b2 cxxstd=20`

**Comment by MarkusJx** [comment]
Unfortunately I am currently not able to work on these projects. I will get back to you in about one or two weeks.

**Comment by MarkusJx** [comment]
Should've said three weeks, damn. Sorry about that.

Any chance you know how the `cxxstd` flag behaves? Does setting it break compatibility with earlier c++ versions? The [b2 manual](https://www.boost.org/doc/libs/1_84_0/tools/build/doc/html/index.html) doesn't really specify if this is the case.

**Comment by MarkusJx** [comment]
I've created a [release for version 1.84.0](https://github.com/MarkusJx/prebuilt-boost/releases/tag/1.84.0) but didn't add the flag you mentioned, as I didn't want to break backwards compatibility. I hope that's ok.

Closing this issue for now, feel free to reopen or create a new one if you are having any issues.
